# Generated by Django 3.1.7 on 2021-03-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_auto_20210306_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cat',
            new_name='Categ',
        ),
    ]
