# Generated by Django 3.1.7 on 2021-03-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20210306_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ',
            old_name='name',
            new_name='Categ_title',
        ),
    ]
